In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
df=pd.read_csv('kyphosis.csv')

In [6]:
df.head()   #age in months

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kyphosis  81 non-null     object
 1   Age       81 non-null     int64
 2   Number    81 non-null     int64
 3   Start     81 non-null     int64
dtypes: int64(3), object(1)
memory usage: 2.7+ KB

In [8]:
df.describe()

              Age     Number      Start
count   81.000000  81.000000  81.000000
mean    83.654321   4.049383  11.493827
std     58.104251   1.619423   4.883962
min      1.000000   2.000000   1.000000
25%     26.000000   3.000000   9.000000
50%     87.000000   4.000000  13.000000
75%    130.000000   5.000000  16.000000
max    206.000000  10.000000  18.000000

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
df.columns

Index(['Kyphosis', 'Age', 'Number', 'Start'], dtype='object')

In [11]:
X=df[['Age', 'Number', 'Start']]

In [12]:
y=df['Kyphosis']

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

DecisionTreeClassifier

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
dtree=DecisionTreeClassifier()

In [16]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [17]:
y_pred=dtree.predict(X_test)

In [18]:
compare=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

In [19]:
compare

     Actual Predicted
67   absent   present
45  present    absent
61  present   present
77   absent    absent
19   absent    absent
2   present   present
38   absent    absent
1    absent    absent
62   absent   present
65   absent    absent
75   absent    absent
21  present   present
54   absent    absent
39  present    absent
55   absent    absent
10  present    absent
8    absent    absent
4    absent    absent
50   absent    absent
44   absent    absent
24  present    absent
68   absent    absent
9   present    absent
5    absent    absent
17   absent   present

In [20]:
from sklearn.metrics import classification_report

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      absent       0.74      0.82      0.78        17
     present       0.50      0.38      0.43         8

    accuracy                           0.68        25
   macro avg       0.62      0.60      0.60        25
weighted avg       0.66      0.68      0.67        25

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rndfrst=RandomForestClassifier()   #canuse n_estimators=200 or something here, try test which gives more accuracy

In [24]:
rndfrst.fit(X_train,y_train)

RandomForestClassifier()

In [25]:
y_pred=rndfrst.predict(X_test)

In [26]:
compare=pd.DataFrame({"Actual":y_test,"Predicted":y_pred})

In [27]:
compare

     Actual Predicted
67   absent    absent
45  present    absent
61  present   present
77   absent    absent
19   absent    absent
2   present    absent
38   absent    absent
1    absent    absent
62   absent    absent
65   absent    absent
75   absent    absent
21  present   present
54   absent    absent
39  present    absent
55   absent    absent
10  present    absent
8    absent    absent
4    absent    absent
50   absent    absent
44   absent    absent
24  present    absent
68   absent    absent
9   present    absent
5    absent    absent
17   absent    absent

In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      absent       0.74      1.00      0.85        17
     present       1.00      0.25      0.40         8

    accuracy                           0.76        25
   macro avg       0.87      0.62      0.62        25
weighted avg       0.82      0.76      0.71        25

In this situation , we can say that RandomForest works better and provides better accuracy as compared to a DecisionTree

In general, RandomForest gives better accuracy and precision as compared to DecisionTree